Bronze layer - ( raw data layer)

As i know the concept is to convert bronze means only the raw data without doing any modifications

In [0]:
df = spark.read.csv('/Workspace/Users/dehemiweerakoon@gmail.com/databricks-dubai-property-price/dubai_residential_data_2026.csv', header=True)

In [0]:
display(df.limit(5))

INSTANCE_DATE,PROCEDURE_EN,IS_FREE_HOLD_EN,AREA_EN,PROP_SB_TYPE_EN,TRANS_VALUE,ACTUAL_AREA,ROOMS_EN,NEAREST_METRO_EN,NEAREST_MALL_EN,NEAREST_LANDMARK_EN,PROJECT_EN,price_per_sqm,size_category,value_band
2026-01-02,Sale,Free Hold,BURJ KHALIFA,Flat,2600000.0,140.95,2 B/R,Business Bay Metro Station,Dubai Mall,Downtown Dubai,BAHWAN TOWER,18446.26,Premium,High-End
2026-01-02,Sale,Free Hold,BURJ KHALIFA,Flat,2731642.0,134.46,2 B/R,Business Bay Metro Station,Dubai Mall,Downtown Dubai,Imperial Avenue,20315.65,Premium,High-End
2026-03-09,Sale,Free Hold,JUMEIRAH VILLAGE CIRCLE,Flat,620000.0,42.87,Studio,Nakheel Metro Station,Marina Mall,Sports City Swimming Academy,PANTHEON ELYSEE,14462.33,Compact,Entry
2026-03-06,Sale,Free Hold,JUMEIRAH VILLAGE CIRCLE,Flat,540000.0,36.86,Studio,Nakheel Metro Station,Marina Mall,Sports City Swimming Academy,null,14650.03,Compact,Entry
2026-03-06,Sale,Free Hold,INTERNATIONAL CITY PH 1,Flat,515000.0,66.5,1 B/R,Rashidiya Metro Station,City Centre Mirdif,null,null,7744.36,Mid-Size,Entry

In [0]:
df.write.format("delta").mode("overwrite").saveAsTable("bronze_data_dubai_residental_data")

Silver step

1.  Remove duplicates
2. fix or standardize data types
3. handle missing/null values
4. filter out clearly bad records

In [0]:
# to convert this data first to sliver first load bronze and then fix
bronze_data = spark.read.table("bronze_data_dubai_residental_data")
display(bronze_data.limit(15))

INSTANCE_DATE,PROCEDURE_EN,IS_FREE_HOLD_EN,AREA_EN,PROP_SB_TYPE_EN,TRANS_VALUE,ACTUAL_AREA,ROOMS_EN,NEAREST_METRO_EN,NEAREST_MALL_EN,NEAREST_LANDMARK_EN,PROJECT_EN,price_per_sqm,size_category,value_band
2026-01-02,Sale,Free Hold,BURJ KHALIFA,Flat,2600000.0,140.95,2 B/R,Business Bay Metro Station,Dubai Mall,Downtown Dubai,BAHWAN TOWER,18446.26,Premium,High-End
2026-01-02,Sale,Free Hold,BURJ KHALIFA,Flat,2731642.0,134.46,2 B/R,Business Bay Metro Station,Dubai Mall,Downtown Dubai,Imperial Avenue,20315.65,Premium,High-End
2026-03-09,Sale,Free Hold,JUMEIRAH VILLAGE CIRCLE,Flat,620000.0,42.87,Studio,Nakheel Metro Station,Marina Mall,Sports City Swimming Academy,PANTHEON ELYSEE,14462.33,Compact,Entry
2026-03-06,Sale,Free Hold,JUMEIRAH VILLAGE CIRCLE,Flat,540000.0,36.86,Studio,Nakheel Metro Station,Marina Mall,Sports City Swimming Academy,null,14650.03,Compact,Entry
2026-03-06,Sale,Free Hold,INTERNATIONAL CITY PH 1,Flat,515000.0,66.5,1 B/R,Rashidiya Metro Station,City Centre Mirdif,null,null,7744.36,Mid-Size,Entry
2026-03-06,Sale,Free Hold,INTERNATIONAL CITY PH 1,Flat,342000.0,44.0,Studio,Rashidiya Metro Station,City Centre Mirdif,null,null,7772.73,Compact,Entry
2026-03-09,Sale,Free Hold,PALM JUMEIRAH,Flat,22000000.0,561.12,3 B/R,Jumeirah Beach Resdency,Marina Mall,Burj Al Arab,W Residences Dubai - The Palm,39207.3,Premium,Ultra-Premium
2026-03-06,Sale,Free Hold,BURJ KHALIFA,Hotel Apartment,1675000.0,85.35,1 B/R,Buj Khalifa Dubai Mall Metro Station,Dubai Mall,Downtown Dubai,THE DISTINCTION,19625.07,Mid-Size,High-End
2026-03-06,Sale,Free Hold,REMRAAM,Flat,1100000.0,93.4,2 B/R,null,null,Motor City,REMRAAM,11777.3,Spacious,Mid-Market
2026-03-06,Sale,Free Hold,DUBAI MARINA,Flat,1333500.0,41.37,Studio,Jumeirah Beach Resdency,Marina Mall,Burj Al Arab,BAY CENTRAL WEST & CENTRAL TOWERS,32233.5,Compact,Mid-Market
2026-03-06,Sale,Free Hold,JUMEIRAH VILLAGE CIRCLE,Flat,1500000.0,84.69,1 B/R,Dubai Internet City,Mall of the Emirates,Sports City Swimming Academy,Binghatti Phantom,17711.65,Mid-Size,High-End
2026-03-06,Sale,Free Hold,BURJ KHALIFA,Flat,1900000.0,80.74,1 B/R,Business Bay Metro Station,Dubai Mall,Downtown Dubai,CLAREN 1,23532.33,Mid-Size,High-End
2026-03-06,Sale,Free Hold,JUMEIRAH VILLAGE CIRCLE,Hotel Apartment,620000.0,43.81,Studio,Dubai Internet City,Mall of the Emirates,Sports City Swimming Academy,Milano Giovanni Boutique Suites,14152.02,Compact,Entry
2026-03-06,Sale,Free Hold,JUMEIRAH LAKES TOWERS,Flat,2700000.0,192.96,3 B/R,Damac Properties,Marina Mall,Burj Al Arab,null,13992.54,Premium,High-End
2026-03-06,Sale,Free Hold,INTERNATIONAL CITY PH 1,Flat,890000.0,105.1,2 B/R,Rashidiya Metro Station,City Centre Mirdif,null,HDS SUNSTAR 1,8468.13,Spacious,Mid-Market

In [0]:
standard_column_names = []
for rec in bronze_data.columns:
    standard_column_names.append(rec.lower())
standard_column_names

['instance_date',
 'procedure_en',
 'is_free_hold_en',
 'area_en',
 'prop_sb_type_en',
 'trans_value',
 'actual_area',
 'rooms_en',
 'nearest_metro_en',
 'nearest_mall_en',
 'nearest_landmark_en',
 'project_en',
 'price_per_sqm',
 'size_category',
 'value_band']

In [0]:
silver_df = bronze_data.toDF(*standard_column_names)
display(silver_df.limit(5))

instance_date,procedure_en,is_free_hold_en,area_en,prop_sb_type_en,trans_value,actual_area,rooms_en,nearest_metro_en,nearest_mall_en,nearest_landmark_en,project_en,price_per_sqm,size_category,value_band
2026-01-02,Sale,Free Hold,BURJ KHALIFA,Flat,2600000.0,140.95,2 B/R,Business Bay Metro Station,Dubai Mall,Downtown Dubai,BAHWAN TOWER,18446.26,Premium,High-End
2026-01-02,Sale,Free Hold,BURJ KHALIFA,Flat,2731642.0,134.46,2 B/R,Business Bay Metro Station,Dubai Mall,Downtown Dubai,Imperial Avenue,20315.65,Premium,High-End
2026-03-09,Sale,Free Hold,JUMEIRAH VILLAGE CIRCLE,Flat,620000.0,42.87,Studio,Nakheel Metro Station,Marina Mall,Sports City Swimming Academy,PANTHEON ELYSEE,14462.33,Compact,Entry
2026-03-06,Sale,Free Hold,JUMEIRAH VILLAGE CIRCLE,Flat,540000.0,36.86,Studio,Nakheel Metro Station,Marina Mall,Sports City Swimming Academy,null,14650.03,Compact,Entry
2026-03-06,Sale,Free Hold,INTERNATIONAL CITY PH 1,Flat,515000.0,66.5,1 B/R,Rashidiya Metro Station,City Centre Mirdif,null,null,7744.36,Mid-Size,Entry

In [0]:
# I first checked whether need to change the data type
silver_df.dtypes

[('instance_date', 'string'),
 ('procedure_en', 'string'),
 ('is_free_hold_en', 'string'),
 ('area_en', 'string'),
 ('prop_sb_type_en', 'string'),
 ('trans_value', 'string'),
 ('actual_area', 'string'),
 ('rooms_en', 'string'),
 ('nearest_metro_en', 'string'),
 ('nearest_mall_en', 'string'),
 ('nearest_landmark_en', 'string'),
 ('project_en', 'string'),
 ('price_per_sqm', 'string'),
 ('size_category', 'string'),
 ('value_band', 'string')]

from their i see the instance_date , trans_value , actual_area and the price_per_sqm is not in correct data format i convert as following

In [0]:
from pyspark.sql.functions import col
silver_df = silver_df.withColumn('instance_date',col('instance_date').cast('date'))
silver_df = silver_df.withColumn('trans_value',col('trans_value').cast('double'))
silver_df = silver_df.withColumn('actual_area',col('actual_area').cast('double'))
silver_df = silver_df.withColumn('price_per_sqm',col('price_per_sqm').cast('double'))
silver_df.dtypes

[('instance_date', 'date'),
 ('procedure_en', 'string'),
 ('is_free_hold_en', 'string'),
 ('area_en', 'string'),
 ('prop_sb_type_en', 'string'),
 ('trans_value', 'double'),
 ('actual_area', 'double'),
 ('rooms_en', 'string'),
 ('nearest_metro_en', 'string'),
 ('nearest_mall_en', 'string'),
 ('nearest_landmark_en', 'string'),
 ('project_en', 'string'),
 ('price_per_sqm', 'double'),
 ('size_category', 'string'),
 ('value_band', 'string')]

In [0]:
silver_df.summary().toPandas()

  summary         procedure_en  ... size_category     value_band
0   count                18085  ...         18085          18085
1    mean                 None  ...          None           None
2  stddev                 None  ...          None           None
3     min  Delayed Development  ...       Compact          Entry
4     25%                 None  ...          None           None
5     50%                 None  ...          None           None
6     75%                 None  ...          None           None
7     max     Sell Development  ...      Spacious  Ultra-Premium

[8 rows x 15 columns]

In [0]:
# drop the duplciate data
print(silver_df.count())
silver_df = silver_df.dropDuplicates()
print(silver_df.count())

18085
18085

In [0]:
from pyspark.sql.functions import col, sum

# Loop through every column and count how many values are null
null_counts = silver_df.select([
    sum(col(c).isNull().cast("int")).alias(c) 
    for c in silver_df.columns
])

# Display the results as a neat table in Databricks
display(null_counts)

instance_date,procedure_en,is_free_hold_en,area_en,prop_sb_type_en,trans_value,actual_area,rooms_en,nearest_metro_en,nearest_mall_en,nearest_landmark_en,project_en,price_per_sqm,size_category,value_band
0,0,0,0,0,0,0,362,3572,3753,1652,4067,0,0,0

In here all the null value columns are string format not the double or the integer

In [0]:
silver_df = silver_df.fillna("Unknown", subset=["rooms_en", "nearest_mall_en", "nearest_landmark_en","project_en","nearest_metro_en"])

In [0]:
silver_df.summary().toPandas()

  summary         procedure_en  ... size_category     value_band
0   count                18085  ...         18085          18085
1    mean                 None  ...          None           None
2  stddev                 None  ...          None           None
3     min  Delayed Development  ...       Compact          Entry
4     25%                 None  ...          None           None
5     50%                 None  ...          None           None
6     75%                 None  ...          None           None
7     max     Sell Development  ...      Spacious  Ultra-Premium

[8 rows x 15 columns]

The number values are on  the range with noraml range so we dont need to fix those values

In [0]:
silver_df.write.format("delta").mode("overwrite").saveAsTable("silver_dubai_property")
display(silver_df.limit(10))

instance_date,procedure_en,is_free_hold_en,area_en,prop_sb_type_en,trans_value,actual_area,rooms_en,nearest_metro_en,nearest_mall_en,nearest_landmark_en,project_en,price_per_sqm,size_category,value_band
2026-01-02,Sale,Free Hold,BURJ KHALIFA,Flat,2600000.0,140.95,2 B/R,Business Bay Metro Station,Dubai Mall,Downtown Dubai,BAHWAN TOWER,18446.26,Premium,High-End
2026-01-02,Sale,Free Hold,BURJ KHALIFA,Flat,2731642.0,134.46,2 B/R,Business Bay Metro Station,Dubai Mall,Downtown Dubai,Imperial Avenue,20315.65,Premium,High-End
2026-03-09,Sale,Free Hold,JUMEIRAH VILLAGE CIRCLE,Flat,620000.0,42.87,Studio,Nakheel Metro Station,Marina Mall,Sports City Swimming Academy,PANTHEON ELYSEE,14462.33,Compact,Entry
2026-03-06,Sale,Free Hold,JUMEIRAH VILLAGE CIRCLE,Flat,540000.0,36.86,Studio,Nakheel Metro Station,Marina Mall,Sports City Swimming Academy,Unknown,14650.03,Compact,Entry
2026-03-06,Sale,Free Hold,INTERNATIONAL CITY PH 1,Flat,515000.0,66.5,1 B/R,Rashidiya Metro Station,City Centre Mirdif,Unknown,Unknown,7744.36,Mid-Size,Entry
2026-03-06,Sale,Free Hold,INTERNATIONAL CITY PH 1,Flat,342000.0,44.0,Studio,Rashidiya Metro Station,City Centre Mirdif,Unknown,Unknown,7772.73,Compact,Entry
2026-03-09,Sale,Free Hold,PALM JUMEIRAH,Flat,2.2E7,561.12,3 B/R,Jumeirah Beach Resdency,Marina Mall,Burj Al Arab,W Residences Dubai - The Palm,39207.3,Premium,Ultra-Premium
2026-03-06,Sale,Free Hold,BURJ KHALIFA,Hotel Apartment,1675000.0,85.35,1 B/R,Buj Khalifa Dubai Mall Metro Station,Dubai Mall,Downtown Dubai,THE DISTINCTION,19625.07,Mid-Size,High-End
2026-03-06,Sale,Free Hold,REMRAAM,Flat,1100000.0,93.4,2 B/R,Unknown,Unknown,Motor City,REMRAAM,11777.3,Spacious,Mid-Market
2026-03-06,Sale,Free Hold,DUBAI MARINA,Flat,1333500.0,41.37,Studio,Jumeirah Beach Resdency,Marina Mall,Burj Al Arab,BAY CENTRAL WEST & CENTRAL TOWERS,32233.5,Compact,Mid-Market

In [0]:
from pyspark.sql.types import BooleanType
import pyspark.sql.functions as F
silver_df = silver_df.withColumn(
    "is_free_hold_en",
    F.when(F.lower(F.col("is_free_hold_en")).contains("Non Free Hold"), False)
     .otherwise(True).cast(BooleanType())
)

In here I convert the column data into a standard format, In here i have converted the data types of the columns into the 'date' and 'double' when the necessary columns found. After that we drop duplicates in here. then count the number of null values in each column. but we found that null values are in the string columns only . then i replaced the null value with default values. the data ranges are normal the price and the numbers are in the range so we dont need to correct them and convert them in here. In the last the is_free_hold_en convert into boolean value telling true and false

# Gold

Gold: Aggregate your Silver table into the summary view(s) needed to answer your problem 
statement (e.g. totals, averages, trends over time, top-N breakdowns by category).

### 1.  Gold 1: Avg price / price-per-sqft by district (area_en)

In [0]:
import pyspark.sql.functions as F

gold_1_df = silver_df.groupBy("area_en").agg(
    F.avg("actual_area").alias("avg_actual_area"),
    F.avg("trans_value").alias("avg_trans_value"),
    F.avg("price_per_sqm").alias("avg_price_per_sqm"),
    F.count("trans_value").alias("count_trans_value")
).orderBy(F.col("avg_price_per_sqm").desc())
display(gold_1_df)

area_en,avg_actual_area,avg_trans_value,avg_price_per_sqm,count_trans_value
JUMEIRA BAY,302.58,2.965E7,103370.84,2
BLUEWATERS,171.51999999999998,1.1028231104166666E7,59474.33979166665,48
Zaabeel First,169.97625,9662500.0,56861.748750000006,16
PEARL JUMEIRA,172.245,8750000.0,50796.885,2
Trade Center First,118.5953846153846,4913284.615384615,48768.339230769234,13
THE WORLD,37.73,1700000.0,45056.98,1
Al Merkadh,39.95333333333334,1558200.0,42073.753333333334,3
DUBAI WATER CANAL,159.5428846153846,7022354.131538462,39418.07980769232,52
Jumeirah First,142.94608695652173,5402608.695652174,36735.36217391304,23
Marsa Dubai,156.75571428571428,6024385.8902857145,36711.584285714285,35
DUBAI HARBOUR,116.54041095890415,4360117.410958904,36227.96643835616,146
PALM JUMEIRAH,183.7072580645163,6185711.073306454,32940.11798387099,372
LA MER,103.21641025641028,3433547.1794871795,32105.418461538462,39
Um Suqaim Third,110.45075000000001,3502375.0,31404.99575000001,40
Al Wasl,77.39208333333333,2473120.75,31366.4425,24
BURJ KHALIFA,127.72692771084348,4234264.723240962,30711.98266265063,830
CITY WALK,172.5594017094018,5253850.843589743,29518.7687179487,117
MINA RASHID,121.73727272727272,3602727.272727273,29050.513636363637,11
JUMEIRAH LIVING,133.89633333333333,4071808.0179999997,28738.898666666664,30
Zaabeel Second,109.65685185185187,3165909.8331481484,28354.586851851844,54
DUBAI MARINA,102.51501529051997,2162532.9696432217,28344.918481141678,981
THE LAKES,163.32952380952378,4754994.666666667,27665.03095238096,21
DUBAI INVESTMENT PARK FIRST,160.63680851063828,2583198.1914893617,27361.492340425513,47
DUBAI CREEK HARBOUR,108.33475199999998,2824009.377328,26074.72992000001,625
Business Bay,74.33285714285714,1821250.5157142857,25538.181428571428,14
DUBAI HILLS,91.32403061224487,2340743.0097959186,25467.42015306121,392
TECOM SITE A,188.1512765957447,4813588.8321276605,24549.808723404254,47
MEYDAN ONE,47.300089686098644,1175353.935941704,24304.139551569504,446
Hadaeq Sheikh Mohammed Bin Rashid,74.0937037037037,1756991.7037037036,23587.84666666667,27
DUBAI MARITIME CITY,135.808,3090426.3333333335,22818.160666666667,15
JUMEIRAH BEACH RESIDENCE,161.18716417910446,3780054.5031343284,22749.528756218908,201
BUSINESS BAY,100.58798899755502,2301076.3660452324,22534.629645476733,1636
Al Kifaf,135.4538775510204,3005603.9591836734,21850.07979591837,49
MBR DISTRICT 1,104.47827586206893,2287944.650517241,21477.52206896552,58
SOBHA HEARTLAND,91.2827111111111,1961748.9531777776,21252.92555555555,450
BARSHA HEIGHTS,119.0448251748252,2346456.3151748255,20942.612937062946,143
DUBAI HEALTHCARE CITY - PHASE 1,75.3,1487500.0,20866.535,2
DUBAI HEALTHCARE CITY - PHASE 2,79.30262910798125,1618064.7771830985,20747.097089201885,213
THE GREENS,102.19540669856455,2116335.1496650716,20549.583157894755,209
Al Satwa,85.97938775510204,1689246.1259183674,20497.26551020408,49
Port Saeed,121.60750000000002,2308585.25,19189.875,8
AL BARARI,124.25631067961172,2410100.8533009705,19054.904174757252,103
JUMEIRAH HEIGHTS,213.3375,4043750.0,18982.13125,8
JADDAF WATERFRONT,118.93849999999996,2218161.2666666666,18970.21666666666,60
MBR DISTRICT 7,55.851612903225806,1031218.7741935484,18697.26064516129,31
MEYDAN AVENUE,116.02999999999999,1993176.4286842104,18305.457894736843,76
JUMEIRAH LAKES TOWERS,106.91608974358981,2020385.351076923,18293.81970512822,780
SUFOUH GARDENS,121.586,2054801.48,16848.305999999997,25
JUMEIRAH VILLAGE TRIANGLE,61.970618181818125,943429.9157818182,16778.695636363624,275
NAD AL SHEBA GARDENS,105.974,1726374.6,16616.428000000004,5
Trade Center Second,238.74266666666668,3950000.0,16440.914,15
Madinat Dubai Almelaheyah,84.75,1345944.0,15815.925,2
Jabal Ali First,67.4940625,1063822.84375,15736.265312499998,32
Al Yelayiss 2,97.72846774193543,1452272.3870967743,15254.17588709678,124
Al Kheeran,183.656875,2793957.3125,15003.12625,16
DUBAI SCIENCE PARK,82.26119047619048,1251448.4991666665,14982.086666666664,84
ARJAN,67.4340976331361,983226.2407396449,14878.51309171598,676
MUDON,102.70583333333336,1468055.9166666667,14867.133333333333,12
JUMEIRAH GOLF,110.89542857142858,1698465.6719999998,14825.779714285714,35
Muhaisanah First,136.40045454545455,1980242.0281818183,14676.519545454545,22
SILICON OASIS,86.60913533834581,1083444.5859210526,14675.838101503756,532
DAMAC HILLS,69.03987654320986,984926.6981481481,14568.6970781893,243
TOWN SQUARE,80.57189300411518,1103107.154691358,14508.749053497946,243
EMIRATE LIVING,534.91,7700000.0,14394.94,1
JUMEIRAH VILLAGE CIRCLE,78.52348614609572,1079517.8843828717,14365.803329974811,1985
AL FURJAN,88.32747252747251,1241129.422065934,14274.803934065938,455
DUBAI STUDIO CITY,53.26857819905215,714926.1919905213,14188.33061611374,211
DOWN TOWN JABAL ALI,51.786984126984144,644220.1301587302,14027.734603174602,63
DMCC-EZ2,49.39666666666667,680349.0,13741.706666666665,3
Warsan First,62.08333333333335,835645.4545454546,13580.12272727273,33
Al Barsha First,82.24307692307693,1074230.7692307692,13105.384615384617,13
Mirdif,174.95571428571427,2546435.8409523806,12925.11428571428,42
EMAAR SOUTH,129.0482352941176,1575836.5882352942,12871.30294117647,34
Wadi Al Safa 7,57.672051282051285,700907.5641025641,12685.585897435898,39
DUBAI INDUSTRIAL CITY,63.42818181818181,797408.4545454546,12345.388181818182,11
LIVING LEGENDS,86.62482758620689,1077174.7462068966,12235.679655172413,29
MAJAN,85.9257324840764,1014067.1973885352,12081.42044585987,314
Madinat Hind 4,53.17441176470588,616975.6861764706,11906.192352941182,68
DUBAI SOUTH,71.26197943444735,780284.4124935732,11283.140179948581,389
MOTOR CITY,152.4156927710845,1795906.8290361445,11230.572951807233,332
DUBAI SPORTS CITY,71.90427466150862,765477.2185299806,11153.432127659566,517
AL WAHA,160.565,1772500.0,11038.380000000001,4
DUBAI PRODUCTION CITY,67.14483146067427,728072.4658988765,10971.763511235955,356
Wadi Al Safa 3,97.57625,1062377.6029166668,10910.645833333334,24
DISCOVERY GARDENS,73.66266910420475,769746.3192138941,10780.553455210238,547
Rega Al Buteen,85.75,905000.0,10553.94,1
Al Barshaa South Third,80.32333333333332,843333.3333333334,10503.19,3
REMRAAM,93.20548387096771,945702.8530645161,10423.737500000005,124
Nad Al Hamar,115.07466666666667,1200769.8666666667,10422.643999999998,15
AL KHAIL HEIGHTS,90.27678571428571,889013.5714285715,10149.264821428571,56
LIWAN,86.95281954887217,845072.1206766918,10019.721917293235,266
DUBAI LAND RESIDENCE COMPLEX,83.82422145328722,819803.3974740483,9832.909238754335,289
DUBAI WATER FRONT,89.2,739375.0,8486.75375,8
INTERNATIONAL CITY PH 2 & 3,65.11158878504675,531517.713457944,8268.21929906542,214
DUBAI INVESTMENT PARK SECOND,109.78813008130079,773472.3448780483,8003.853577235773,123
CITY OF ARABIA,88.05199999999999,703933.0,7972.0160000000005,5
Al Qusais Industrial Fourth,55.576666666666675,450170.3333333333,7955.983333333334,3
INTERNATIONAL CITY PH 1,67.69386731391592,519151.5538187701,7852.477330097086,618

###  Gold 2: Avg price / volume by property type & room count

In [0]:
gold_2_df = silver_df.groupBy('prop_sb_type_en','rooms_en').agg(
    F.avg("trans_value").alias("avg_trans_value"),
    F.avg("price_per_sqm").alias("avg_price_per_sqm"),
    F.count("trans_value").alias("count_trans_value")
).orderBy(F.col("avg_price_per_sqm").desc())
display(gold_2_df)

prop_sb_type_en,rooms_en,avg_trans_value,avg_price_per_sqm,count_trans_value
Hotel Apartment,5 B/R,2.3E7,73473.04,1
Hotel Apartment,4 B/R,1.4375E7,53749.94,6
Flat,5 B/R,3.3054985083333332E7,52092.7875,12
Hotel Rooms,Studio,890172.1788679245,49938.59449685533,318
Hotel Apartment,3 B/R,8288127.5,42619.24324999999,40
Hotel Apartment,Unknown,2000000.0,41476.57,1
Hotel Rooms,1 B/R,1629973.6764705882,34969.894411764704,34
Hotel Apartment,2 B/R,4531404.223333334,33397.149185185175,135
Show Rooms,Unknown,4651828.0,32937.96,1
Shop,Unknown,2915328.338122271,31844.855065502205,229
Flat,6 B/R,2.65244375E7,30125.77,4
Flat,4 B/R,1.04697627576875E7,28222.496000000003,160
Hotel Apartment,1 B/R,2131629.245384616,27171.805562130186,169
Office,Unknown,2929503.747107438,26465.231818181815,121
Flat,PENTHOUSE,8248850.066666666,24743.576000000005,15
Shop,Shop,4028283.0321428576,23616.43991071428,112
Flat,3 B/R,4413202.9845611015,22538.12788296039,1162
Office,Office,3034114.5149871134,20784.957268041253,776
Flat,2 B/R,2368129.2471008305,18832.477674970294,4215
Flat,Unknown,1150000.0,18199.08,1
Hotel Rooms,2 B/R,1500440.142857143,16314.74857142857,7
Hotel Apartment,Studio,625145.4938121546,16314.644254143643,181
Flat,Studio,664443.9968729098,16037.714768673375,3588
Flat,1 B/R,1187199.1298422285,15867.558571217942,6782
Workshop,Unknown,680349.0,13741.706666666665,3
Stacked Townhouses,2 B/R,2150000.0,13334.99,1
Flat,Office,2900000.0,12545.42,1
Stacked Townhouses,3 B/R,2325000.0,10380.01,2
Show Rooms,Shop,1300000.0,9859.69,1
Warehouse,Unknown,4538020.583333333,6082.766666666666,6
Office,Shop,304500.0,3013.96,1

### Gold 3: Monthly transaction volume & price trend

In [0]:
gold_3_df = silver_df.withColumn('year_month',F.date_format('instance_date','yyyy-MM')).groupBy('year_month').agg(
                F.sum("trans_value").alias("sum_trans_value"),
                
                F.avg("price_per_sqm").alias("avg_price_per_sqm"),
                F.sum("price_per_sqm").alias("sum_price_per_sqm"),
                F.avg('trans_value').alias('avg_trans_value'))
display(gold_3_df)

year_month,sum_trans_value,avg_price_per_sqm,sum_price_per_sqm,avg_trans_value
2026-01,7.731977073730001E9,18131.92066468254,7.310790412E7,1917653.0440798614
2026-03,4.39762191332E9,17963.65604564314,4.329241106999996E7,1824739.383120332
2026-02,8.176597520909999E9,18956.656240037493,8.086909551999995E7,1916689.5267018282
2026-04,4.406871810610001E9,19410.521847519187,4.811868366000006E7,1777681.246716418
2026-05,3.5780238949299994E9,19385.033151904987,3.917715199999998E7,1770422.5110984659
2026-06,4.659258337610002E9,18200.20204733727,4.6137512189999975E7,1837971.7308126239
2026-07,6.4772250652E8,18981.550204678366,6491690.170000001,1893925.4576608187

In [0]:
gold_1_df.write.format("delta").mode("overwrite").saveAsTable("gold_price_by_area")
gold_2_df.write.format("delta").mode("overwrite").saveAsTable("gold_price_by_type")
gold_3_df.write.format("delta").mode("overwrite").saveAsTable("gold_monthly_view")